server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shadabbahadara/microservices-practice/config-store
          search-paths:
           - '*service'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
           