server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shadabbahadara/microservices-practice/config-store
          search-paths:
           - '*service'